function printBanner(sourceDescription, statusMessage)
    % printBanner - OpenVEHICLE ASCII banner plus a one-line status
    % message, shared by any Vehicle construction method that wants to
    % report progress to the console (e.g. FromExcelFile).
    disp([...
        '_______                    ___    ________________  ________________________________';...
        '__  __ \_____________________ |  / /__  ____/__  / / /___  _/_  ____/__  /___  ____/';...
        '_  / / /__  __ \  _ \_  __ \_ | / /__  __/  __  /_/ / __  / _  /    __  / __  __/   ';...
        '/ /_/ /__  /_/ /  __/  / / /_ |/ / _  /___  _  __  / __/ /  / /___  _  /___  /___   ';...
        '\____/ _  .___/\___//_/ /_/_____/  /_____/  /_/ /_/  /___/  \____/  /_____/_____/   ';...
        '       /_/                                                                          '...
        ]) ;
    disp('====================================================================================')
    disp(sourceDescription)
    disp(statusMessage)
    disp('====================================================================================')
end
