function printBanner(vehicleName, trackName)
    % printBanner - OpenLAP ASCII banner plus vehicle/track/date/time
    % summary.
    lg = [...
        '_______                    _____________________ ';...
        '__  __ \______________________  /___    |__  __ \';...
        '_  / / /__  __ \  _ \_  __ \_  / __  /| |_  /_/ /';...
        '/ /_/ /__  /_/ /  __/  / / /  /___  ___ |  ____/ ';...
        '\____/ _  .___/\___//_/ /_//_____/_/  |_/_/      ';...
        '       /_/                                       '...
        ] ;
    disp(lg)
    disp('=================================================')
    disp("Vehicle: "+vehicleName)
    disp("Track:   "+trackName)
    disp("Date:    "+datestr(now,'dd/mm/yyyy'))
    disp("Time:    "+datestr(now,'HH:MM:SS'))
    disp('=================================================')
end
