function printBanner(sourceDescription, statusMessage)
    % printBanner - OpenTRACK ASCII banner plus a one-line status
    % message, shared by any Track construction method that wants to
    % report progress to the console.
    disp([...
        '_______                    ____________________________________ __';...
        '__  __ \______________________  __/__  __ \__    |_  ____/__  //_/';...
        '_  / / /__  __ \  _ \_  __ \_  /  __  /_/ /_  /| |  /    __  ,<   ';...
        '/ /_/ /__  /_/ /  __/  / / /  /   _  _, _/_  ___ / /___  _  /| |  ';...
        '\____/ _  .___/\___//_/ /_//_/    /_/ |_| /_/  |_\____/  /_/ |_|  ';...
        '       /_/                                                        '...
        ]) ;
    disp('==================================================================')
    disp(sourceDescription)
    disp(statusMessage)
    disp('==================================================================')
end
